/**
 * HelpPanels.tsx
 *
 * The app's REFERENCE panels — the three documents the "?" chooser (? / F1) opens:
 * the full control list, what each view mode shows, and how each statistic is computed.
 *
 * Split out of PolylineTool because this is documentation, not behaviour: it is the
 * longest block in the app and the one most often edited, and every edit to it was
 * previously a diff against the same file as the pointer handlers and the render loop.
 *
 * PER CLAUDE.md: `ControlsList` is the SINGLE SOURCE OF TRUTH for the app's controls.
 * Whenever a control is added, removed, or changed, it is updated in the SAME change —
 * moving it here does not relax that, it just gives it its own file.
 */

/**
 * The Help button opens a submenu that picks ONE of three reference panels. Each
 * panel reuses the same floating-popup chrome; only its title + body differ.
 */
export type HelpPanel = "controls" | "stats" | "views";
/** Title shown (UPPERCASED by CSS) at the top-left of each help reference panel. */
export const HELP_PANEL_TITLE: Record<HelpPanel, string> = {
  controls: "Control List",
  stats: "Statistics Info",
  views: "View Modes Info",
};

/**
 * The full controls / keybindings reference. Extracted so the list lives in ONE
 * place — it is rendered inside the help popup (the Help button in the top-right utility
 * bottom-right). Previously this lived inline in the left tool panel; moving it
 * here keeps the panel focused on active controls and avoids duplicating the docs.
 */
export function ControlsList() {
  return (
    <ul className="help">
      <li><b>Select</b> (<b>V</b>) is the pointer tool, first in the bottom bar and active in <b>both phases</b> · <b>Plan:</b> click the <b>drawn shape</b> (anywhere inside a closed footprint, or on the outline) to select it as ONE object, or a <b>reference image</b> to pick that instead — <b>whatever is drawn on top wins</b>, so since underlays always sit beneath the drawing, a click inside a traced footprint picks the <b>building</b>; click the image <b>outside</b> the footprint to pick the image · grips beat bodies, so a selected object's grips stay grabbable wherever they fall · only <b>one object at a time</b> is ever selected · <b>drag</b> the selection to move it, or drag a <b>corner / edge grip</b> to resize it; corners keep the proportions, <b>Shift</b> stretches freely · moving and scaling are <b>one undo step</b> each, and a plain click that moves nothing costs no history · perimeter vertices stay inert while Select is armed (they belong to the Pen), so a click is never ambiguous · <b>Elevations:</b> it is the <b>default</b> tool and the neutral pick state — click a <b>wall border</b>, then a <b>cell</b> · <b>V</b> arms it from anywhere — it is the universal ESCAPE from whatever is in hand, putting every other tool down (including <b>unloading a Glazing brush</b>), so the bar can never show two armed tools · it is the <b>resting tool</b>: whenever no other tool is armed, Select is — with one exception, <b>on arrival</b>, where the <b>Pen</b> is already in hand so an empty canvas can be drawn on immediately — <b>Esc</b> drops the selection but keeps Select in hand, putting <i>any other</i> tool down returns to it, and so does switching phase · clicking empty canvas clears the selection without putting the tool down</li>
      <li><b>Pen</b> (bottom bar, after <b>Delete</b>) is the single footprint tool — it replaces the old Draw / Edit pair · while the perimeter is <b>open</b> it DRAWS: each click places the next vertex · once the perimeter is <b>closed</b> it EDITS: drag a vertex to move it, drag a knob to curve, click a segment to insert a vertex, double-click a vertex for a corner · the switch is automatic (closing the loop, or reopening it by erasing an edge, flips the behaviour) and the button's tooltip always says which one is in hand · shown in both phases, active in Plan · it is the tool <b>already in hand when the app opens</b>, so a new sketch can be started with a click and no tool selection</li>
      <li><b>Import</b> (top-right <b>utility bar</b>, beside <b>Export</b>; Plan phase) opens a file browser for a <b>PDF, PNG, JPG or JPEG</b> and places it on the canvas as a <b>reference underlay</b> to trace over — sized to fit the current view and drawn beneath all geometry · the import <b>arms Select and picks the new image</b>, so its grips are ready immediately · select several files to place them all · <b>multi-page PDFs place page 1</b> · Plan phase only</li>
      <li><b>Move / resize an underlay</b> (<b>Select</b> tool) <b>drag</b> the image to move it · drag any of the <b>eight grips</b> to resize — corners keep the original proportions, <b>Shift</b> stretches freely, and edge grips scale one axis · the opposite corner or edge stays pinned · <b>Delete / Backspace</b> removes the selected image · an underlay is <b>always drawn beneath the geometry</b> (the app has no layers, so it can never cover the drawing), though its selection frame and grips stay on top so they are always grabbable · every move, resize, import and delete is <b>undoable</b></li>
      <li><b>Selected image</b> (its own panel, appearing under <b>Statistics</b> only while an underlay is selected) <b>Opacity</b> fades the image so the drawing reads on top · <b>Lock</b> pins its placement so tracing can't nudge it — no drag, no resize, and its grips disappear (the frame stays) · a locked image is still <b>selectable</b>, so you can always click it to bring this panel back and <b>Unlock</b> it · <b>Delete</b> removes it · the panel vanishes when you deselect · images are saved with the project</li>
      <li><b>Click</b> place vertex</li>
      <li><b>Type a number</b> (after the first vertex) sets the next segment's exact <b>length</b> — the cursor aims the direction, the rubber band snaps to the typed length · <b>Enter</b> places the vertex at that length · <b>.</b> for decimals · <b>Backspace</b> edits · <b>Esc</b> cancels the entry · hold <b>Shift</b> to also lock the angle to 15°</li>
      <li><b>Click-drag</b> pull out curve handles</li>
      <li><b>V</b> select tool · <b>A / L</b> arc / line segments (keyboard only — the Create section's Line / Arc switch was removed)</li>
      <li><b>Plan / Elevations</b> (segmented switch with icons, <b>top-center</b> of the canvas) is the app's <b>phase switch</b> — click a side to move between the footprint (<b>Plan</b>) and the unrolled wall strip (<b>Elevations</b>); the active phase is highlighted · <b>Elevations</b> stays disabled until the perimeter has enough geometry to unroll · switching plays the unroll / fold transition · the phase also decides <b>which tools the bottom bar shows</b></li>
      <li><b>Bottom tool bar</b> leads with the same run in <b>both</b> phases — <b>Pan · Select · Delete · Pen</b> — so the tools you reach for most never move · after a divider, the <b>curtain-wall cluster</b> (<b>Floor Lines · CW Type · Centerlines · Framing · Glazing</b>) and <b>Export</b> appear in <b>Elevations</b> only · the cluster runs roughly in the order the work does — <b>Floor Lines</b> leads because it is the only one needing nothing selected first · <b>Pen</b> doubles as the edit tool: it draws vertices on an open shape and edits them once the perimeter closes, so there is no separate Edit button</li>
      <li><b>Project</b> (<b>Overview</b> window, first section) owns the current sketch on ONE row: the <b>name field</b> (placeholder <i>Project Name</i>) renames it — once saved, typing updates the saved project live and the Projects list follows; before the first save it holds the name <b>Save</b> will apply · <b>Save</b> stores the sketch in Projects (also <b>Ctrl+S</b>; needs at least two vertices) · <b>New</b> starts a blank project</li>
      <li><b>Location</b> (<b>Overview</b> window) defaults to <b>Omaha, NE</b>, pre-resolved, so the solar tools read a real site from the start · type an address or "lat, lng" and press <b>Enter</b> to move the project somewhere else · the <b>☀</b> button on the same row opens the <b>Solar Study</b>, since the site is what it reads · resolved <b>offline</b> — no account or connection needed · the readout beneath reports the matched place, elevation, and time zone</li>
      <li><b>Project previews</b> follow the phase: in <b>Plan</b> every thumbnail shows the <b>aerial</b> (top-down) massing, and switching to <b>Elevations</b> animates them round to the <b>3-D</b> ¾ view, so the previews read in the same terms as the main canvas · <b>drag</b> a preview to spin it or <b>double-click</b> to toggle, either of which overrides the phase default until you switch phase again</li>
      <li><b>Panels</b> — two columns. <b>Left:</b> <b>Overview</b> (holds <b>Project</b>, with the project list inside it, then <b>Location</b>), and <b>Display</b> (<b>View mode</b> and <b>Visibility</b>) beneath it. <b>Right:</b> the <b>utility bar</b>, then <b>Statistics</b>, then the <b>Selected image</b> window while an underlay is picked · they are <b>fixed in place</b>: no dragging, no collapsing — each is always where you left it · <b>Statistics</b> grows downward as readings are switched on, and the window under it shrinks to the space left rather than being pushed off-screen</li>
      <li><b>Click first vertex / Double-click / Enter</b> close</li>
      <li><b>Esc</b> cancel polyline</li>
      <li><b>Backspace</b> remove last (draw) / delete selected (edit)</li>
      <li><b>Shift</b> constrain to 15°</li>
      <li><b>Crosshairs</b> light-grey guide lines track the cursor across the canvas once you've started a perimeter (drawing or editing its vertices)</li>
      <li><b>Edit:</b> drag vertex · drag knobs · Alt-drag curve · click segment to insert</li>
      <li><b>Double-click vertex</b> make corner</li>
      <li><b>Shift-click a vertex</b> delete it (perimeter view) · or arm <b>Delete</b> and click (or click-drag across) vertices to remove them (the targeted vertices turn red)</li>
      <li><b>Wheel / pinch</b> zoom (at cursor) · <b>Middle-drag</b> pan (any view, any tool) · <b>right-click does nothing</b> — panning is <b>Space + drag</b>, so the right button is left free rather than kept as a duplicate gesture, and the browser's context menu stays suppressed over the canvas</li>
      <li><b>Pan</b> (first in the bottom tool bar, left of <b>Select</b>) arms the navigation tool — <b>click-drag</b> the canvas with the LEFT button to move the view · blue while armed, and the cursor becomes a <b>grab hand</b> · works in every view and takes precedence over the other tools (a drag never draws, selects, or erases while it's on) · <b>Esc</b> or re-click the button to finish · clicking any other tool button also releases it</li>
      <li><b>Hold Space</b> + <b>click-drag</b> pans <b>temporarily</b> from any tool (the <b>Pan</b> button lights up while held) — release Space to drop straight back to the tool you were using, with no toggling</li>
      <li><b>Undo</b> · <b>Redo</b> (↶ ↷, first in the top-right <b>utility bar</b>) step the document back and forward · shortcuts <b>Ctrl+Z</b> / <b>Ctrl+Y</b> (Ctrl+Shift+Z also redoes)</li>
      <li><b>Ctrl+S</b> save perimeter → mini-window (top-right)</li>
      <li><b>Statistics</b> (its own window, top-right under the utility bar) picks ONE live reading from a compact chooser (<b>scroll the wheel over it</b> to cycle without opening the list) — <b>General</b>, <b>Irradiance (W/m²)</b>, <b>Insolation (kWh/m²)</b>, <b>WWR</b>, or <b>VLT</b> — and shows it underneath; it opens on <b>General</b> · <b>General</b> reads from the <b>very first frame</b> — an empty canvas shows <b>Walls 0 · Perimeter 0 · Footprint area 0 · Extents 0 × 0</b> and every figure climbs as you place vertices (footprint area stays 0 until the loop closes, since an open chain encloses nothing); the four analysis reads are <b>elevation-only</b> and stay dimmed in the Plan phase · the selection is <b>shared across views, but only for stats that read on both sides</b> — <b>General</b> carries between the <b>Plan</b> and the elevation views, while Irradiance / Insolation are wall reads, so the <b>Plan phase shows None</b> for them (your pick is remembered and restored on return)  · the readout itself now renders <b>in this panel</b> (it used to float on the canvas, where zooming in pushed it out of view) — wall reads follow the <b>selected wall border</b>, or the left-most elevation when none is selected · <i>what each mode shows and how it's computed is in the "?" menu's <b>Statistics Info</b></i></li>
      <li><b>Solar Study</b> (<b>☀ Solar</b> button, on the address row in the <b>Location</b> section — the same place <b>Save</b> and <b>New</b> sit on the Project row) opens the sun-path popup for the <b>loaded project</b> · click again (or the popup's ×) to close it · disabled until a project is saved or loaded, since the study reads a saved project's massing</li>
      <li><b>Visibility</b> (<b>Display</b> window) shows / hides drawn elements without deleting them — a two-column grid with one cell each for <b>Dims</b> (dimensions), <b>Floors</b> (floor lines), <b>Centerlines</b>, <b>Framing</b>, and <b>Glazing</b> (the per-cell type hatches) — hover any for its full name · the order runs from the <b>drawing aids</b> down through the <b>curtain wall itself</b>, roughly the order the cluster tools build it in · click a row to toggle it (the eye closes and the row fades when hidden) · rows dim when that element can't exist in the current view · these are the <b>single source of truth</b>: <b>no view mode ever auto-hides them</b></li>
      <li><b>Demo</b> (top-right <b>utility bar</b>, after Undo / Redo — its border <b>pulses blue until you have run it once</b> this visit, then goes quiet for good) plays a <b>guided tour</b> that <b>builds</b> an example building in front of you rather than loading a finished one — it draws the footprint, resolves a real site and opens the <b>Solar Study</b>, unrolls the walls, then works through <b>Floor Lines · CW Type · Centerlines · Framing · Glazing</b>, cycles the <b>View modes</b>, reads the <b>Statistics</b>, and ends by marquee-selecting walls and opening the <b>Export</b> dialog — it <b>stops there and downloads nothing</b>, leaving the DXF buttons for you · each card names the <b>gesture</b> the tool actually needs (which ones are a <b>drag</b> rather than a click) · <b>twelve cards, and it never advances on its own</b>: each one animates and then waits · <b>Next</b> / <b>Enter</b> / <b>→</b> advance · <b>Back</b> / <b>←</b> replays the previous step · <b>Exit</b>, <b>×</b>, <b>Esc</b>, or the <b>Demo</b> button again leaves at any point, <b>keeping everything built so far</b> · the tour drives the app's real state, so the result is an ordinary editable project (saved as <i>Demo — Bowfront Tower</i>) · an <b>unsaved sketch is filed into your projects first</b>, so starting the demo never costs you work</li>
      <li><b>Export</b> (last in the top-right <b>utility bar</b>; Elevations phase) arms the <b>wall-selection marquee</b> in the elevation views (blue while armed; disabled until the geometry is unrolled) · <b>click-drag</b> a box over the panels to select every wall it touches (selected walls highlight <b>green</b>) · <b>release</b> opens the export dialog · <b>Esc</b> cancels</li>
      <li><b>Export dialog</b> shows a 3D preview of <b>only the selected walls</b> (<b>drag</b> to orbit · drag the title bar to move) · <b>Revit / AutoCAD / Rhino</b> buttons download a <b>DXF</b> that preserves real dimensions in <b>feet</b> · click outside to flash · <b>Esc</b> / <b>×</b> to close</li>
      <li><b>Unrolling</b> unravels the geometry — edges are unrolled clockwise into equal-length strips, each wall becoming one elevation panel</li>
      <li><b>Switching phase</b> — use the <b>Plan / Elevations</b> switch at the top of the canvas (it replaced the Projects popup's "Unroll Geometry" button) · <b>Esc</b> from the full strip folds back to the plan too (the last step of the cell → wall border → strip → plan chain)</li>
      <li><b>Unroll transition</b> entering the elevations plays the footprint standing up as the 3D massing and unrolling flat, so you can see which wall becomes which panel · <b>Fold to Plan</b> plays the SAME transition <b>in reverse</b>, folding the walls back up in the order they unrolled · <b>click</b>, <b>any key</b>, or <b>wheel / pinch</b> skips either direction straight to its destination — the result is identical, only sooner</li>
      <li><b>Closing the perimeter saves the project automatically</b> — there is no save-first step before unrolling · the <b>Save</b> button still creates a separate new option from the current sketch</li>
      <li><b>Floor Lines</b> (bottom-center tool bar, Elevations) — available as soon as you are in the elevation views, with <b>no prerequisites</b>: floor plates are a building datum, not a curtain-wall property, and row centerlines snap to them, so levels are usually the first thing you set · <b>click</b> arms the tool to drop horizontal level lines (click the canvas to add, click a line to remove; Esc or re-click to finish) · show / hide them with <b>Display</b> window ▸ <b>Visibility ▸ Floor lines</b> in the Display window · the ground <b>0′</b> line is permanent (always present, can't be deleted)</li>
      <li><b>Floor-plate snap</b> after the first plate above ground, new plates snap to multiples of that floor-to-floor height · <b>Shift</b> bypasses the snap (free / grid placement)</li>
      <li><b>Unravel:</b> drag a panel top to resize</li>
      <li><b>Layer navigation:</b> a <b>single click</b> on a panel drills DEEPER (elevation strip → <b>Wall Border</b>) · in the <b>Wall Border</b> view a click on a cell <b>acts on that cell</b> (paints it when the <b>Glazing</b> brush is loaded, otherwise selects it), so a <b>double-click</b> on a cell is what enters the single-cell zoom · <b>click a different panel</b> switches focus straight to it · <b>click the empty canvas</b> in the <b>Wall Border</b> view <b>deselects</b> any selected cells first (dimensions revert to the grid); <b>clicking again</b> with nothing selected collapses the dimensions to the panel's <b>overall length + height</b> — the <b>camera never zooms out</b> · <b>Esc</b> steps back one layer at a time (cell → wall border → strip → plan)</li>
      <li><b>Hover a cell</b> (Panels view, a split panel zoomed-in) highlights the individual grid cell under the cursor, showing the panel is subdivided into navigable cells</li>
      <li><b>Wall Border dimensions</b> follow the layer: the <b>Unroll Elevations</b> strip labels each border with its <b>overall length + height</b> · <b>clicking inside a panel</b> (not its top edge — that resizes) zooms in and switches to the <b>per-column / per-row grid</b> — a <b>width</b> label per column along the top and a <b>height</b> label per row along the left (the panel's height field is hidden here — drag the top edge to resize) · <b>selecting cells</b> replaces the grid with each selected cell's dimensions on <b>all four edges</b> (width on top + bottom, height on left + right) — parked <b>inside</b> the cell so several selections never overlap · <b>click the empty canvas</b> to deselect (back to the grid), and <b>again</b> (nothing selected) to collapse to the panel's <b>overall length + height</b> — the camera stays zoomed in on the border (use the top tabs to return to the strip)</li>
      <li><b>Click a cell</b> (<b>Wall Border</b> view) selects it (<b>Shift+click</b> = all cells of that Material ID) — or <b>paints</b> it when the <b>Glazing</b> brush is loaded · <b>double-click</b> a cell instead to <b>zoom into it</b> (the single-cell view), since the single click is taken by the cell action</li>
      <li><b>Cells view</b> dimensions the selected cell on all four sides: a <b>width</b> label on the top and bottom edges, a <b>height</b> label on the left and right edges</li>
      <li><b>Hover an edge</b> (Assembly view) of the selected cell highlights that edge <b>red</b> (top / right / bottom / left, one at a time) to mark it as selected</li>
      <li><b>Statistics anchor</b> — a <b>soft red glow</b> around a wall border marks the one whose numbers the <b>Statistics</b> window is reading (<b>Irradiance · Insolation · WWR · VLT</b>) · it follows the <b>selected</b> border, and falls back to the <b>left-most</b> elevation when nothing is selected, so the figures are always attributable to a wall you can see · it appears only while one of those readings is on, and it is the ONLY marker of which wall is meant — the readings themselves carry no border caption</li>
      <li><b>Click a panel</b> (Unroll Elevations) selects + zooms it (its width/height labels turn grey) and enables the cluster buttons that only need a border — <b>CW Type</b>, <b>Centerlines</b>, and <b>Glazing</b> (bottom-center tool bar) · <b>Framing</b> stays disabled until that panel has both a CW Type and a centerline · clicking the empty canvas <b>deselects cells</b> first, then <b>clicking again</b> shows the panel's overall length + height — the camera stays put</li>
      <li><b>← / → arrow keys</b> (while zoomed into a wall border) jump to the <b>previous / next border</b> along the strip — the same animated zoom-in as clicking the neighbouring panel, wrapping around the loop · the focused border also lights <b>red on the Projects thumbnail</b> (as if moused over) so you can track which wall is in focus</li>
      <li><b>CW Type</b> (second in the Elevations cluster, after Floor Lines) assigns the curtain-wall system <b>per panel</b> — select a panel, then click (chevron ▾ marks the menu) to choose <b>Stick System</b> or <b>Unitized System</b> · the button is <b>blue while its menu is open</b>, the same way <b>Glazing</b> lights — in this row, blue always means "this button owns your next click" · the button shows the selected panel's "CW Type: <i>name</i>" · it gates only <b>Framing</b>, which genuinely reads it (Stick and Unitized are different interactions) — <b>Floor Lines</b> and <b>Centerlines</b> are plain geometry and need no type · a panel holds only ONE system, so switching its type <b>clears that panel's framing of the other system</b> (its centerlines are kept)</li>
      <li><b>Framing</b> (bottom-center tool bar, after Centerlines) needs BOTH of its prerequisites for real reasons: at least one <b>centerline</b> on the selected panel (offsets are measured from them) and a <b>CW Type</b> (Stick and Unitized are different interactions) · it acts in the <b>Wall Border</b> tab · with the <b>Stick System</b>, hover a panel's <b>vertical</b> or <b>horizontal</b> grid lines (the hovered set highlights, since they adjust together) then <b>click-drag</b> to set a framing (mullion) offset to <b>either side</b> in <b>0.25′</b> increments — dragging one vertical line offsets ALL vertical lines in that panel the same (likewise for horizontal) · with the tool armed, <b>clicking a different wall border</b> (away from this panel's lines) reframes to it with <b>Framing still in hand</b>, so you can move between borders and keep editing without disarming and re-selecting · <b>clicking the empty white canvas</b> (off any panel) deselects the tool · show / hide framing with <b>Display</b> window ▸ <b>Visibility ▸ Framing</b> in the Display window</li>
      <li>with the <b>Unitized System</b>, hover a cell's centerlines to highlight the <b>single nearest edge</b> of the cell under the cursor, then <b>click-drag</b> to inset that one edge <b>into the cell</b> in <b>0.25′</b> increments · hold <b>Shift</b> while dragging to inset <b>all four edges</b> of that cell together · each framed edge draws the solid frame face inset into the cell AND turns the affected <b>centerline segment solid</b> on top of the dashed centerline (the framed mullion) · the edit <b>mirrors live to every same-shape (Material ID) cell</b> across all elevations/panels — editing one cell updates all identical cells project-wide (see the <b>View mode</b> list's Material ID colours / <b>Unique cells</b> count for the groups)</li>
      <li><b>Select cells</b> (<b>Wall Border</b> tab, <b>no Glazing brush loaded</b>) — <b>click a cell</b> to select just that one (it highlights blue); <b>click it again</b> to deselect it · <b>click-drag across cells</b> to sweep-select every cell the cursor crosses (a fresh selection starting from the pressed cell) · <b>Shift+click</b> a cell to select <b>every cell sharing its Material ID</b> across the whole project · a plain click replaces the previous selection · <b>click the empty white canvas</b> (off any panel) <b>clears the whole selection</b> · selecting drives the <b>per-cell dimensions</b></li>
      <li><b>Glazing</b> (right of Framing) is a <b>paint tool: pick the material first, then say where it goes</b> · click it to open the <b>None · Vision · Spandrel · Opaque</b> chooser (drop-up, same rules as the <b>CW Type</b> menu) and pick a type — that <b>loads the brush</b> and assigns nothing yet · enabled whenever a <b>wall border is focused</b> (no selection needed), blue while the chooser is open or a brush is loaded, and the button reads <b>"Glazing: <i>type</i>"</b> so you can always see what a click will paint · <b>the button always opens the chooser</b>, so <b>switching material is one click</b> even with a brush already loaded · to put the tool down, press <b>Esc</b> or <b>V</b>, arm another tool, or click the <b>already-loaded type</b> in the chooser to unload it — any of these unloads the brush, so the button never stays blue while something else owns the click · each type paints its own <b>hatch</b> on the cell · show / hide the hatches with <b>Display</b> window ▸ <b>Visibility ▸ Glazing</b></li>
      <li><b>Paint cells</b> (with a Glazing brush loaded) — <b>click a cell</b> to assign the loaded type to it · <b>click-drag across cells</b> to sweep a run of them (they highlight as you go) and <b>release to assign</b> the whole stroke in a <b>single undoable step</b> · a fast drag still catches every cell on the path · <b>Shift+click</b> a cell paints <b>every cell sharing its Material ID</b> across the whole project at once · <b>None</b> is a brush like any other — painting with it <b>clears</b> the type (back to untyped, no hatch) · painting a cell that already has that type <b>changes nothing and costs no undo step</b> · the loaded type is <b>marked in the chooser</b>, and clicking that marked entry <b>unloads</b> it · while a brush is loaded it <b>owns the click</b>, so <b>double-click no longer drills into a cell</b> — press <b>Esc</b> to put the brush down first</li>
      <li><b>Centerlines</b> (enabled once a wall border is selected — <b>no CW Type needed</b>, since divisions are plain geometry) arms the divide tool — <b>no modifier keys</b>: the cursor's position inside the panel picks BOTH the spacing and the direction · the panel is split by its two <b>diagonals</b> into four zones, and the lines you get run <b>parallel to the nearest edge</b> — sweep across the middle (nearer the left/right ends) for <b>equal-width columns</b>, or move toward the <b>top or bottom edge</b> for <b>equal-height rows</b> · moving further out adds bays, so the same drag sets fewer/wider or more/narrower, with a live dimension showing the resulting column width or row height · a wall elevation is far wider than tall, so most of it reads as columns and rows are a short move away · <b>click</b> places the split, and the direction <b>locks the moment you press</b> so dragging to re-pick the spacing can never flip it · if <b>floor plates</b> cross the panel the rows snap to them — an array line lands on every floor plate and each band between plates is evenly subdivided · with the tool armed, <b>clicking a different wall border</b> reframes to it with <b>Centerlines still in hand</b> · <b>clicking the empty white canvas</b> (off any panel) deselects the tool · show / hide centerlines with <b>Display</b> ▸ <b>Visibility ▸ Centerlines</b> · Esc or re-click the button to finish</li>
      <li><b>Delete</b> (bottom bar, after the first divider, beside <b>Pen</b> — present in both phases) arms the erase tool and works in BOTH views · <b>Plan phase:</b> hover a perimeter <b>vertex</b> (it turns <b>red</b>) and <b>click</b> to delete it, or <b>click-drag</b> across several vertices to remove them all in one stroke (committed as one undo step; dropping below 3 points reopens the shape) · hover a perimeter <b>edge</b> away from its corners (closed shape only) to highlight that segment <b>red</b> and <b>click</b> to remove it — <b>reopening the loop there while keeping both vertices</b> — or <b>click-drag</b> along the boundary to erase several segments at once · any vertex left <b>alone</b> by losing both its walls (e.g. between two erased edges) is <b>auto-deleted</b> too (it pre-highlights red) ·<b>Unravel view:</b> <b>hover</b> near a panel's centerline <em>or</em> a floor plate to highlight it, <b>click</b> deletes it, and <b>click-drag</b> across multiple lines erases them all in one stroke (a fast drag still catches every line on the path), committed as one undo step · erasing a panel's centerline also <b>clears that panel's framing</b> on that axis (the same way adding a centerline does — re-apply framing afterwards), so no frame bars linger along the border without their centerlines · the default <b>0′ ground floor line</b> can't be deleted · Esc or re-click the button to finish · mutually exclusive with Centerlines/Framing/Floor Lines</li>
      <li><b>View mode</b> (<b>Display</b> window; elevation views only) picks how cells are drawn — purely visual, arms no tool · click a cell in the <b>two-column grid</b>: <b>Technical</b>, <b>Material ID</b>, <b>Orientation</b> (Orientation Heatmap), <b>Clean</b>, or <b>Shadows</b> — hover any of them for its full name · <b>no view ever auto-hides floor lines, centerlines, framing, or dimensions</b> — those are controlled ONLY by the <b>Visibility</b> rows above · <i>what each mode shows and how it's computed is in the "?" menu's <b>View Modes Info</b></i></li>
      <li><b>Hover an edge</b> (edit mode) highlights that edge's line on the active mini-window thumbnail · in unravel, hovering a panel lights its wall instead</li>
      <li><b>Project list</b> (<b>Overview</b> ▸ <b>Project</b>): click load (fits the shape to the view) · drag preview to rotate · double-click preview to toggle top-down / 3-D · <b>double-click a name to rename</b> · drag a name to re-order · <b>⧉ duplicate</b> the whole project (perimeter, elevations, framing — everything) into a new <i>Option</i> · <b>× delete</b> — <b>undoable</b> with Ctrl+Z (Ctrl+Y redoes) · saving, naming and New live in the <b>Overview</b> window ▸ <b>Project</b>, and <b>Demo</b> in the top-right utility bar</li>
      <li><b>Solar Study</b> (☀ popup) draws a 3D <b>sun-path dome</b> around the massing from real solar geometry · <b>drag the title bar</b> to move the popup anywhere on screen — freely over the header / footer, kept at least half on-screen · drag the dome to rotate · double-click for an aerial top-down view (synced with the thumbnail) · <b>Orientation dial</b> — drag the needle (or type degrees) to set the drawing's North relative to the cardinal directions · <b>Date</b> and <b>Solar time</b> sliders move the sun along its path (with a live altitude / azimuth readout) · <b>Solar time ⇄ Clock</b> — click the time slider's label to switch which convention it reads and writes; clock time converts through the site's longitude, time zone, and the equation of time (daylight saving included for the date studied), and the opposite reading is always shown beneath · <b>Latitude</b> field — set by resolving the Location address, or type it directly · <b>Location</b> field inherits the sketch's address and resolves it <b>offline</b> the same way the left panel does, showing the matched place, elevation, and time zone · settings are saved with the sketch</li>
      <li><b>Location</b> (left panel) type an address and press <b>Enter</b> (or click away) to locate the sketch — resolved <b>offline</b> from a bundled place database, so it needs no account, key, or connection · you can type literal coordinates instead (<b>"41.26, -95.94"</b>, N/S/E/W suffixes accepted) for a site no database lists · on a match the field <b>rewrites itself to the matched place</b> ("123 Main St, Omaha, NE" becomes "Omaha, Nebraska, US") so the text and the site driving the study always agree — typed coordinates keep their numbers instead, since a place label would round them to that city's centre · the readout under the field adds the <b>latitude/longitude, elevation, and time zone</b>, and ambiguous names (the several Springfields) offer <b>"Did you mean"</b> buttons to correct the guess in one click, rewriting the field to match · resolution is <b>city-level</b>, which moves the sun by well under a degree · a blank field means no location; an address that matches nothing says so and leaves the study on its previous site · saved with the sketch and shared with the Solar Study popup</li>
      <li><b>New</b> (<b>Overview</b> window ▸ <b>Project</b>, beside <b>Save</b>) clears the canvas to a fresh, blank project (your <b>saved projects are kept</b>) · it returns to the <b>Plan</b> phase and leaves the <b>Pen in hand</b>, so you can start drawing the next footprint immediately — the same state the app opens in · to see the whole workflow instead, run <b>Demo</b> from the top-right utility bar</li>
      <li><b>? or F1</b> opens the reference chooser — <b>Control List</b>, <b>Statistics Info</b>, or <b>View Modes Info</b> · <i>(the Help BUTTON was removed from the utility bar; this keystroke is the way in)</i> · the chosen panel is <b>non-modal</b>: it stays open while you pan, zoom, and draw, so it can annotate what is on screen · close it with its <b>×</b>, <b>?</b> / <b>F1</b> again, or <b>Escape</b> · <i>(the old bottom-right <b>?</b> button and the <b>Settings</b> popup have both been removed — the app is <b>feet-only</b>)</i></li>
      {/* Collapse-panel toggle is temporarily removed from the UI; restore this entry when the button returns.
      <li><b>Collapse panel</b> (◂ / ▸ at the bottom-left corner) hides or shows the left tool panel to give the canvas more room</li>
      */}
      <li><b>Edit a loaded entry</b> footprint and elevation-view edits auto-save to that entry (no manual save) · the <b>Save</b> button always creates a NEW entry instead, so it doubles as save a copy'</li>

    </ul>
  );
}

/**
 * VIEW MODES INFO panel ("?" menu → View Modes Info). One entry per View-button display
 * mode: a plain-language sentence on WHAT it shows, then an italic "How:" clause on how
 * it's computed. Kept in sync with the View dropdown (CELL_VIEW_LABELS) + the renderer.
 */
export function ViewModesInfo() {
  return (
    <ul className="help">
      <li><b>Technical</b> the default drafting view — centerlines, framing, and dimensions on a plain background, no cell tinting. <span className="help__how">How: draws the authored geometry as-is; what's visible is governed only by the Floor Lines / Centerlines / Framing eye toggles and the Dim button.</span></li>
      <li><b>Material ID</b> tints every grid cell by its geometric <b>shape</b>, so identical cells across the whole project share one colour and number. <span className="help__how">How: each cell's width × height is rounded to ~0.001′ and bucketed into a shape group; the group index maps to a hue via the golden angle (137.5°), and identical cells fan out in saturation. The Statistics <b>Unique cells</b> count is the number of distinct groups.</span></li>
      <li><b>Orientation Heatmap</b> colours each cell by the <b>compass direction</b> its glass faces and prints that facade's <b>live direct-sun hit %</b> beneath the cardinal. <span className="help__how">How: the facade's outward normal (from the perimeter's winding) is rotated by the Solar Study's North into a true bearing, then mapped onto a cold→hot ramp (N blue · E cyan · S yellow · W red). The % is the cosine of the sun's angle of incidence on the wall — cos(altitude)·cos(sun-azimuth − wall-bearing) at the Solar Study's current day + hour — shown as 100% (sun square-on) down to 0% (grazing or sun behind the wall), or "—" when the sun is below the horizon.</span></li>
      <li><b>Clean</b> a presentation view — the glass panels fill <b>white</b> behind the framing. <span className="help__how">How: the same geometry as Technical with cell infill forced white; the per-button visibility toggles still apply.</span></li>
      <li><b>Shadows</b> a 2.5D presentation — every framing bar reads as raised and casts a hard <b>drop shadow</b> onto the adjacent glass. <span className="help__how">How: built on Clean — each frame bar projects a shadow quad onto neighbouring glass only (never onto frame infill), its length scaling with zoom; the geometry is drawn monochrome while hover highlights stay coloured. <b>Opaque</b> cells sit nearly <b>flush with the frame</b> rather than recessed, so they still catch a shadow — but a much <b>shorter</b> one (a quarter of the throw the recessed Vision / Spandrel glass gets).</span></li>
    </ul>
  );
}

/**
 * STATISTICS INFO panel ("?" menu → Statistics Info). One entry per Statistics reading:
 * a plain-language sentence on WHAT it shows, then an italic "How:" clause on how it's
 * computed. Kept in sync with STATS_MODES + core/radiation.ts.
 */
export function StatisticsInfo() {
  return (
    <ul className="help">
      <li><b>Readings are a set, not a choice</b> — each chip at the top of the <b>Statistics</b> window toggles that reading on or off independently, and every one that is on renders below, stacked in the order listed here · so <b>General</b> and <b>Irradiance</b> can be read at the same time rather than flipped between · the window grows downward to fit and its body scrolls once it reaches full height · chips for wall-orientation readings are <b>disabled in Plan</b>; readings already on are kept, not dropped, and return with the <b>Elevations</b> phase</li>
      <li><b>Which wall the numbers are about</b> — <b>Irradiance</b>, <b>Insolation</b>, <b>WWR</b> and <b>VLT</b> each report ONE facade, so while any of them is on, that wall border carries a <b>soft red glow</b> on the canvas — the glow is the whole answer, so the readings print no border caption of their own · it is the <b>selected border</b> if you have clicked one, otherwise the <b>left-most</b> elevation — which is why the glow matters even when you have selected nothing · <b>General</b> totals the whole strip, so it anchors to no wall and glows nothing</li>
      <li><b>General</b> — live geometric totals for the current view. <span className="help__how">Method: read directly from the drawn geometry. Plan → wall count, perimeter length, footprint area (shoelace), bounding box. Elevation → segment count, unwrapped length, facade area (Σ width × height), unique-cell count.</span></li>
      <li><b>Irradiance (W/m²)</b> — clear-sky solar irradiance on the selected wall, as a month × hour heatmap. <span className="help__how">Method: G = I_b·cos θ + I_d,sky + I_d,gnd. Beam I_b from Hottel clear-sky transmittance (solar zenith + the resolved site's real elevation) on the 1367 W/m² solar constant; θ = beam-to-wall incidence from the wall's true compass normal (beam counts only when the sun faces the wall). Diffuse = isotropic sky (Liu–Jordan correlation) + ground-reflected (albedo 0.2). Sun position from spherical astronomy (site latitude + North offset). Clear-sky envelope — no weather file (EPW/TMY) yet.</span></li>
      <li><b>Insolation (kWh/m²)</b> — monthly solar energy on that same wall, as a bar chart. <span className="help__how">Method: integrate Irradiance over each month's representative day (Klein average day) × days in month → kWh/m²·month; Σ over 12 months → the annual <b>kWh/m²·yr</b> total shown on both diagrams.</span></li>
      <li><b>WWR</b> — Window-to-Wall Ratio of the selected wall border (elevation views). <span className="help__how">Method: window = <b>Vision</b> cells; wall = full panel (width × height). Spandrel, Opaque, and unassigned cells count as wall. Reported both ways — <b>Gross Opening</b> = Σ vision cell opening (frames/mullions included); <b>Net Glazing</b> = Σ vision glass infill (frames/mullions excluded). <b>Assigned N / M</b> shows type coverage; ratios are <b>provisional (*)</b> until every cell is typed (unassigned still counted as wall).</span></li>
      <li><b>Cost</b> — order-of-magnitude estimate for the <b>whole facade</b> (every wall border, not the selected one), broken down as a bill. <span className="help__how">Method: two drivers. <b>Infill</b> = each cell's opening area × a rate for its <b>glazing type</b> (Vision $95/ft², Spandrel $70/ft², Opaque $60/ft² — printed on each line). <b>Framing</b> = total linear feet of mullion × $48/ft, counting each panel's perimeter frame plus every interior centerline across the span it covers — so <b>subdividing a panel raises the cost without changing its area</b>, which is true of real curtain wall and is why area-only pricing would mislead. <b>Untyped cells are never priced</b> (no guessed rate is hidden inside the result): they are listed as an unpriced remainder and the total is marked <b>provisional (*)</b> — a FLOOR that assigning them can only raise. <b>Cost / area</b> is the total over the full facade area, the figure facade work is benchmarked in. Supply + install only — no engineering, escalation, or regional factor. Rates are the single source of truth in <b>core/cost.ts</b>.</span></li>
      <li><b>VLT</b> — daylight transmittance of the selected wall border (elevation views). <span className="help__how">Method: per-type visible transmittance — <b>Vision</b> 70% (clear/low-E IGU), <b>Spandrel</b> and <b>Opaque</b> 0%. <b>Effective aperture</b> = glass-area-weighted VT over the whole panel = Net WWR × glazing VT — the standard daylighting metric (light passes only through the glass infill). <b>Assigned N / M</b> coverage; <b>provisional (*)</b> until the border is fully typed.</span></li>
    </ul>
  );
}
